 os: osx
     
    

addons:
  homebrew:
    casks:

before_deploy:
    brew install go
    brew install FiloSottile/musl-cross/musl-cross
    brew install mingw-w64
    brew install go
    brew install uxp 


go build -x -v -ldflags "-s -w" -o cloudrev-macos && upx -9 cloudrev-macos ||echo "编译请检查runtime"

env CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build  -v -ldflags "-s -w" -o cloudrev_x64.exe && upx -9 cloudrev_x64.exe ||echo "win64编译失败"

env CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64w64-mingw32-g++ GOOS=windows GOARCH=386 go build  -v -ldflags "-s -w" -o cloudre_x86.exe && upx -9 cloudre_x86.exe ||echo "win32编译失败"

env CGO_ENABLED=1 CC=x86_64-linux-musl-gcc GOOS=linux GOARCH=amd64 go build -ldflags "-linkmode external -extldflags -static -s -w"   -o cloudreve_linux-64 && upx -9 cloudreve_linux-64 || echo "linux编译失败"
